### PR TITLE
Devo

### PR DESCRIPTION
**Pull request by nickbrazeau**
Finish Homework 2

### CODE REVIEW

**Comment by nickbrazeau** [comment]
this shouldn't be merge. Using this PR as a comment thread

**Comment by mikedolanfliss** [comment]
Gotcha, Nick. So we can generally order PRs around the homework and then comment here around the commits until that he is done. I like it! Let's hit this PR together in person next week.

**Comment by mikedolanfliss** [comment]
(though I'm still a bit confused hope I know which PR I'm committing to if they're are multiple PRs open...)

**Comment by nickbrazeau** [comment]
Hey Mike,

Agreed… This is definitely a gap in my knowledge, as I haven’t used pull requests like this before. I also am unclear on if you can attach specific code to the pull request or if you always have to merge to the master branch. I’ll try and play around this weekend.

Thanks for your patience! I don’t usually use GitHub this way, so this is great (usually it’s one person just pushing to the master branch and then passing the project off).

Thanks and all the best,
Nick

On Jul 5, 2018, at 6:47 PM, Mike Dolan Fliss <notifications@github.com<mailto:notifications@github.com>> wrote:


(though I'm still a bit confused hope I know which PR I'm committing to if they're are multiple PRs open...)

**Pull request closed without merging**
